In [32]:
from tensorflow import keras

In [33]:
#load Data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
#x_test, y_test = 처음 보는 데이터를 학습시켰을 때 정확도를 보기위한 데이터변수

In [48]:
y_train.shape

(60000, 10)

In [35]:
for i in range(5):
    print(y_train[i])

5
0
4
1
9


In [36]:
#keras를 사용해 5 -> [0, 0, 0, 0, 0, 1, 0, 0, 0, 0] 이렇게 바꿈
#마지막이 10인거는 카테고리가 10개라서
#자동차, 기차, 사람을 구분하는 거면 카테고리 '3'
y_train = keras.utils.to_categorical(y_train, 10) 
y_test = keras.utils.to_categorical(y_test, 10) 

In [37]:
for i in range(5):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [50]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [39]:
x_train = x_train.reshape(60000, 28*28)
x_test = x_test.reshape(10000, 28*28)

In [40]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [41]:
model = keras.Sequential()
model.add(keras.layers.Dense(32, activation='sigmoid', input_shape=(784,)))
model.add(keras.layers.Dense(32, activation='sigmoid'))
model.add(keras.layers.Dense(10, activation='sigmoid'))

In [42]:
#optimizer(s)**** s붙여야함
optimizer = keras.optimizers.SGD(lr=0.1)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 32)                25120     
_________________________________________________________________
dense_7 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_8 (Dense)              (None, 10)                330       
Total params: 26,506
Trainable params: 26,506
Non-trainable params: 0
_________________________________________________________________


In [43]:
model.fit(x_train, y_train, batch_size=128, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
469/469 [==============================] - 1s 2ms/step - loss: 1.6710 - accuracy: 0.6395 - val_loss: 0.9911 - val_accuracy: 0.8136
Epoch 2/10
469/469 [==============================] - 1s 2ms/step - loss: 0.7841 - accuracy: 0.8267 - val_loss: 0.6112 - val_accuracy: 0.8536
Epoch 3/10
469/469 [==============================] - 1s 2ms/step - loss: 0.6014 - accuracy: 0.8404 - val_loss: 0.5910 - val_accuracy: 0.8459
Epoch 4/10
469/469 [==============================] - 1s 2ms/step - loss: 0.5969 - accuracy: 0.8305 - val_loss: 0.5669 - val_accuracy: 0.8394
Epoch 5/10
469/469 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.8414 - val_loss: 0.5750 - val_accuracy: 0.8312
Epoch 6/10
469/469 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.8388 - val_loss: 0.4983 - val_accuracy: 0.8511
Epoch 7/10
469/469 [==============================] - 1s 2ms/step - loss: 0.5117 - accuracy: 0.8448 - val_loss: 0.4828 - val_accuracy: 0.8538
Epoch 

In [44]:
model.evaluate(x_test, y_test)

313/313 [==============================] - 0s 902us/step - loss: 0.4767 - accuracy: 0.8487


[0.4767287075519562, 0.8486999869346619]